### ISSUE TITLE
Small text when hovering over the notch

### ISSUE THREAD

**Issue by yasingunaydiin** [iamharshdev/boring.notch#1]
Step 1: Hover over the notch.
Step 2: Observe text is small.

See attached image.
<img width="500" alt="Scherm­afbeelding 2024-08-03 om 23 59 22" src="https://github.com/user-attachments/assets/4976af28-e9ce-419b-b586-4037e662fe5d">

**Comment by iamharshdev** [comment]
That totally makes sense. I'll get it fixed in the latest release.
