### ISSUE TITLE
The rest of the icons aren't showing. 

### ISSUE THREAD

**Issue by yasingunaydiin** [iamharshdev/boring.notch#11]
You sent a screenshot with a few features in the "add a close button" issue I created but as you can see, there's no such thing. When I randomly click, it does close and a page opens up but no icons.

<img width="500" alt="Scherm­afbeelding 2024-08-05 om 18 41 51" src="https://github.com/user-attachments/assets/0f469528-2123-4d75-a51f-5044f2a9294d">

**Comment by iamharshdev** [comment]
This is a issue with system wide light mode turned on. Turn it off from settings. I'll fix this in upcoming release.

<img width="827" alt="Screenshot 2024-08-06 at 1 52 09 PM" src="https://github.com/user-attachments/assets/9d05f0e5-71ea-4667-991f-569fd49f854f">
