### ISSUE TITLE
Issue with external display

### ISSUE THREAD

**Issue by skitnay** [iamharshdev/boring.notch#14]
When I focus on the external display and then hover over the BoringNotch, it moves down and to the right 
<img width="1710" alt="Screenshot 2024-08-07 at 3 30 07 PM" src="https://github.com/user-attachments/assets/4d063ee6-5229-494f-b6f6-c0807d9fd4b2">

**Comment by iamharshdev** [comment]
Send wallpaper first. Then i'll fix it. @skitnay

**Comment by skitnay** [comment]
This is the wallpaper from the macOS Sequoia beta 😁@iamharshdev 
<img width="358" alt="Screenshot 2024-08-07 at 10 06 48 PM" src="https://github.com/user-attachments/assets/a8974e3b-9a34-424d-87d8-c618b83b5aaf">

**Comment by jamesjingyi** [comment]
It would be great if I could choose which display to put BoringNotch on, since my main display is set as my external monitor rather than my MacBook's screen (which is the one with the notch!)
