### ISSUE TITLE
Notch opens up before really touching the notch

### ISSUE THREAD

**Issue by yasingunaydiin** [iamharshdev/boring.notch#2]
The notch opens up before you touch it. Its a bit annoying when it opens when you want to change browser tabs.
Fix: Make it open up when the user touches the black part or at least a bit more higher.

**Comment by iamharshdev** [comment]
That happens only sometimes I'm trying to resolve that.

**Comment by iamharshdev** [comment]
That only happens if you have the image taking up full space, it doesn't happen with music playing in yt music (mac client) try that it;s weired. @yasingunaydiin

**Comment by yasingunaydiin** [comment]
Hi!
I like the new features! But now with the latest update, with a video in the background, the following happens: 
https://github.com/user-attachments/assets/0484e87b-5d61-46e8-85d0-528c72fe4291

**Comment by iamharshdev** [comment]
> Hi!
> I like the new features! But now with the latest update, with a video in the background, the following happens: 
> https://github.com/user-attachments/assets/0484e87b-5d61-46e8-85d0-528c72fe4291

I'll get this fixed in the upcoming release soon. Thanks.
