### ISSUE TITLE
Remove the icon from the Mac dock

### ISSUE THREAD

**Issue by yasingunaydiin** [iamharshdev/boring.notch#3]
More of an idea that you could incorporate. Make the BoringNotch icon invisible in the dock.

**Comment by iamharshdev** [comment]
Hmmm interesting. I mean i had it there just to show off the logo that i made myself 🥳.

**Comment by yasingunaydiin** [comment]
It looks good! I just thought that would be better, because its an overlay app. Personally i dont want one more thing in the dock hahaha but thats just me.

Some app creators, for example toolbar related, they add a setting to turn it on and off. I’d love that!

**Comment by iamharshdev** [comment]
With the latest release that's fixed @yasingunaydiin
