### ISSUE TITLE
Album cover UI isn't entirely hidden when media is paused

### ISSUE THREAD

**Issue by rahilthehill** [iamharshdev/boring.notch#33]
I am on a 2021 16-inch Macbook pro, and using boring notch has been great (I absolutely love what ya'll are doing) , however there are some issues with paused media, it's supposed to hide the album cover of the media, however on my mac, the album cover is only half covered, I tried to recreate it with a screenshot below, the white part is the actual notch. It's really distracting to see that little part album cover poking out every time media isn't playing.

Also another suggestion, when pausing and playing the notch "snaps" open and closed, maybe a smoother animation for it to open and close would make it look cleaner.

<img width="332" alt="Screenshot 2024-08-11 at 6 23 41 PM" src="https://github.com/user-attachments/assets/6d18e8aa-2f56-40a2-9589-4350f9839bc5">

**Comment by DinahWorld** [comment]
Same issue for me

**Comment by rahilthehill** [comment]
I also noticed this is a issue with the cool face animation when the media is playing which i thought would fit under the same issue. When there is no media playing, there is no problem with the face animation, however when media does start playing, on my 16 inch macbook bro, the right eye and a little bit of the smile poke out of the notch ever so slightly.

**Comment by richardkunkli** [comment]
Hi,
Thank you for the feedback. We have already known about this issue and working on it.
