### ISSUE TITLE
Battery UI misaligned & charging indicator suggestion

### ISSUE THREAD

**Issue by rahilthehill** [iamharshdev/boring.notch#34]
A really small UI nitpick suggestion, I noticed that the battery rectangle is ever so slightly misaligned with the outer box & at the same time the charging indicator is almost impossible to see when the progress bar is more than 50% since the icon is also white, maybe changing it to green or something like what apple does with their battery indicator would work better, once again just a really small observation that would make the overall app look cleaner.

<img width="51" alt="Screenshot 2024-08-12 at 12 23 58 AM" src="https://github.com/user-attachments/assets/e09bc7d2-e0f2-4a80-aaf8-7cc58f9b33d3">

**Comment by richardkunkli** [comment]
Hello,
Thank you, we are currently reworking this feature and soon will be resolved. 🚀
