### ISSUE TITLE
[Visual] Shadow appears too heavy in collapsed mode + Other improvements

### ISSUE THREAD

**Issue by sermelipharo** [iamharshdev/boring.notch#35]
The shadow appears too heavy in collapsed mode. It might be better to have an option to disable it entirely (similar to the Dynamic Island on iOS) and only show it in expanded mode.

Additionally, on the 16" MacBook Pro, the rounded corners look off. It's unclear whether this is due to improper scaling or the use of [circled angles instead of smoothed corners](https://medium.com/@arthurofbabylon/a-smooth-corner-radius-in-ios-54b80aa2d372).  
<img width="218" alt="image" src="https://github.com/user-attachments/assets/4a38d044-305e-4c3c-bc57-cb474973ffb2">

A small feature request: it would be useful to have an option to add a delay before expanding, along with quick options (similar to option-clicking the clock to toggle Focus). For example, user-selectable default behavior like option+hover to keep it collapsed or option+hover to expand. In the first case, option-clicking the tiny cover could open the media source app, and option-clicking the waves could play/pause. In the second case, force-click could replace option-click.

**Comment by richardkunkli** [comment]
Hi,
Thank you for the feedback. I believe the shadow should not appear when collapsed, so it is a bug. We'll fix it. The delayed open is currently under development, the whole behavior of the notch will be reworked for a better user experience. The gesture control seems interesting, we'll consider implementing customizable gestures. (I'm pretty sure we will have this)
