### ISSUE TITLE
Wrong album cover

### ISSUE THREAD

**Issue by alec-c4** [iamharshdev/boring.notch#44]
Album cover isn't updated after track change :(

<img width="657" alt="SCR-20240813-bfzt" src="https://github.com/user-attachments/assets/284fd57c-ebcb-4dd2-b397-2a4c3032c4ff">

Also, I'd like to ask you to add battery percentage information :)

**Comment by skynnes** [comment]
Charging indicator doesn't seem to update either

**Comment by richardkunkli** [comment]
Hi,
Thank you for the feedback. We are aware of this bug and working on a fix. Expected later today as a patch release.
