### ISSUE TITLE
Can't install Boring Notch (Apple cannot check for malicious software)

### ISSUE THREAD

**Issue by Samalander0** [iamharshdev/boring.notch#45]
Hi,

New to MacOS so might be doing something wrong here, but I'm getting the following error with the latest two releases. I have not checked older releases. See screenshot below.

![image](https://github.com/user-attachments/assets/b1e65732-9b60-4392-bd19-74d06afd014b)

**Comment by Carlosmlon** [comment]
Right click on the app icon and click "open". It will show you a similar pop-up but with a button to open it.
