### ISSUE TITLE
Bug with the play/pause button

### ISSUE THREAD

**Issue by Carlosmlon** [iamharshdev/boring.notch#46]
The new version "Romantic Lady" brought back a similar bug to one I reported a few days ago. 

Apple Music has Radio Stations, and when playing one, I can pause it and start playing again, but the app remains on pause. And another is that when playing songs, it plays and pauses, but the play status takes longer to update. 

Thank you in advance for all the work y'all are doing. The UI overhaul is lovely.

I'm attaching a screen video recording (beware of the volume 😬).

https://github.com/user-attachments/assets/ccf255d2-eb28-411e-94a6-ec30082af438

**Comment by iamharshdev** [comment]
We'll fix this in today's hotfix release.

**Comment by cal1b4n** [comment]
This also is happening with Spotify. Play/Pause seems to respond slowly to the actions

**Comment by cal1b4n** [comment]
This issue still persists on Dancing snake version as of now. If you rapidly click Play/Pause it gets messed up

**Comment by iamharshdev** [comment]
I'll look into this
