### ISSUE TITLE
Song title is not changing if the song is part of the same album

### ISSUE THREAD

**Issue by vy28** [iamharshdev/boring.notch#52]
<img width="869" alt="Screenshot 2024-08-13 at 12 54 55 PM" src="https://github.com/user-attachments/assets/c46589c1-4299-4301-a53a-d39ddc7da69a">

**Comment by cal1b4n** [comment]
Can confirm, same thing is happening on my mac

![Screenshot 2024-08-14 at 12 47 10](https://github.com/user-attachments/assets/26813579-3468-4454-9976-020863184bd2)

**Comment by Romachamp** [comment]
Yeah, I reported the same on Discord
