### ISSUE TITLE
Battery icon reappears after restart despite being unchecked in options

### ISSUE THREAD

**Issue by martinloic** [iamharshdev/boring.notch#64]
## Description:
The battery icon reappear after the software is restarted, even though the corresponding option has been unchecked in the settings (the option resets).

## Steps to reproduce:
- Open the software settings.
- Uncheck the option to display the battery icon.
- Save the settings and close the software.
- Restart the software.

## Expected behavior:
The battery icon should not appear after restarting the software, as per the saved settings.

Software version: **Sleeping Snail 🐌**

**Comment by richardkunkli** [comment]
Hi,
Thanks for the feedback. This is not a bug, we currently won't restore user settings on restart. This is because it helps us to address bugs easier and quicker. Will be enabled later.
