### ISSUE TITLE
Add a close app button

### ISSUE THREAD

**Issue by yasingunaydiin** [iamharshdev/boring.notch#8]
I currently have to go to activity monitor to close it 😅

(I know you JUST started creating the app and you probably already have this in your to do list but I wanted to open this issue just in case!)

**Comment by iamharshdev** [comment]
![image](https://github.com/user-attachments/assets/12985614-bab9-4d95-8028-cff855b31a7a)

**Comment by iamharshdev** [comment]
![image](https://github.com/user-attachments/assets/785f8be3-d42e-4dc8-a9ef-186f792e5512)
