### ISSUE TITLE
Unable to install on Macos 14.6.1

### ISSUE THREAD

**Issue by Stargorithm** [iamharshdev/boring.notch#84]
<img width="240" alt="Screenshot 2024-08-31 at 3 44 44 PM" src="https://github.com/user-attachments/assets/7a7a2c93-16bd-4199-8926-42350c9d223b">

**Comment by Alex17450** [comment]
Hi, you have to go in the settings and then in the privacy and security section and then you scroll all the way down and you should see something that will allow you to open the app by putting in your password. Then just re open the app
